import { Mom, Post, Location, Match, Message, Badge, ClassInfo } from './types';

const AVATAR_COLORS = ['#E8836B', '#6BB8A8', '#F5C469', '#5B9BD5', '#D4A0D0', '#E8B87A', '#7BC8A4', '#F08080'];

export function getAvatarColor(name: string): string {
  let hash = 0;
  for (let i = 0; i < name.length; i++) {
    hash = name.charCodeAt(i) + ((hash << 5) - hash);
  }
  return AVATAR_COLORS[Math.abs(hash) % AVATAR_COLORS.length];
}

export function getInitials(name: string): string {
  return name.split(' ').map(n => n[0]).join('').toUpperCase().slice(0, 2);
}

export const CURRENT_USER_ID = 'user_current';

export const currentUser: Mom = {
  id: CURRENT_USER_ID,
  name: 'Sarah Chen',
  age: 32,
  neighborhood: 'Park Slope',
  bio: 'Brooklyn born & raised. Love discovering new coffee shops with my little ones. Always down for a playdate at Prospect Park!',
  interests: ['Coffee', 'Yoga', 'Reading', 'Cooking', 'Playgrounds'],
  kids: [
    { name: 'Mia', age: 3, ageLabel: '3 yrs', gender: 'girl' },
    { name: 'Leo', age: 1, ageLabel: '1 yr', gender: 'boy' },
  ],
  avatar: '',
  photos: [],
  verified: true,
  hangNow: false,
  lastActive: 'now',
  prompts: [
    { question: 'My ideal coffee catch-up looks like...', answer: 'Coffee for me, sandbox for the kids, and great conversation about anything besides parenting tips we already know.' },
    { question: 'On weekends you\'ll find us at...', answer: 'Prospect Park in the morning, then a cozy cafe for lunch. We love exploring new spots!' },
    { question: 'Currently into...', answer: 'Yoga, sourdough baking, and finding the best playgrounds in Brooklyn.' },
  ],
  vibeTags: ['Cappuccino person', 'Park strolls', 'Yoga', 'Foodie mom', 'Go-with-the-flow'],
  coffeeMeetupPreferences: {
    meetupStyle: ['Walk + coffee', 'Long sit-down chat'],
    favoriteSpots: ['Cafe Regular', 'Sey Coffee', 'Winner'],
  },
  comfortSignals: {
    strollerFriendlyOnly: false,
    playgroundAndCafe: 'Either',
    indoorCafeComfort: 'Yes',
  },
  safety: { phoneVerified: true, referredByMember: true, neighborhoodHost: false },
  socialProof: { mutualConnectionsCount: 5, successfulMeetupsCount: 8, ratingAverage: 4.9 },
};

export const discoveryMoms: Mom[] = [
  {
    id: 'mom_1',
    name: 'Jessica Park',
    age: 30,
    neighborhood: 'Carroll Gardens',
    bio: 'Former chef turned stay-at-home mom. I make the best snack bags for the playground. Looking for mom friends who appreciate good food and good company.',
    interests: ['Cooking', 'Baking', 'Wine Tasting', 'Playgrounds', 'Music'],
    kids: [{ name: 'Oliver', age: 2, ageLabel: '2 yrs', gender: 'boy' }],
    avatar: '',
    photos: [],
    verified: true,
    hangNow: true,
    lastActive: '5m ago',
    prompts: [
      { question: 'The way to my heart is...', answer: 'A perfectly pulled espresso and someone who doesn\'t judge my toddler\'s outfit choices.' },
      { question: 'Before kids, I was...', answer: 'A sous chef at a farm-to-table restaurant in Williamsburg. Now I meal-prep like it\'s a competitive sport.' },
      { question: 'I geek out on...', answer: 'Fermentation, sourdough starters, and finding the best pizza slice in Brooklyn.' },
    ],
    vibeTags: ['Foodie mom', 'Home cooking', 'Wine night (kid-free)', 'Playground chats', 'Bakery scouting'],
    coffeeMeetupPreferences: {
      meetupStyle: ['Long sit-down chat', 'Walk + coffee', 'Kid-free evening drink'],
      favoriteSpots: ['Devocion', 'Cafe Regular', 'Colson Patisserie'],
    },
    comfortSignals: {
      strollerFriendlyOnly: false,
      playgroundAndCafe: 'Cafe first',
      indoorCafeComfort: 'Yes',
    },
    safety: { phoneVerified: true, referredByMember: true, neighborhoodHost: false },
    socialProof: { mutualConnectionsCount: 3, successfulMeetupsCount: 5, ratingAverage: 4.8 },
  },
  {
    id: 'mom_2',
    name: 'Amara Okafor',
    age: 34,
    neighborhood: 'Prospect Heights',
    bio: 'Graphic designer working from home. My daughter and I are always looking for creative activities and new friends in the neighborhood.',
    interests: ['Art', 'Design', 'Yoga', 'Museums', 'Coffee'],
    kids: [{ name: 'Zara', age: 4, ageLabel: '4 yrs', gender: 'girl' }],
    avatar: '',
    photos: [],
    verified: true,
    hangNow: false,
    lastActive: '20m ago',
    prompts: [
      { question: 'My ideal coffee catch-up looks like...', answer: 'Art projects, paint everywhere, and coffee while the kids create masterpieces.' },
      { question: 'Before kids, I was...', answer: 'A brand designer at a startup. Still freelancing between nap times and snack breaks.' },
      { question: 'Currently into...', answer: 'Printmaking workshops, museum memberships, and trying every matcha latte in Brooklyn.' },
    ],
    vibeTags: ['Artsy', 'Design-minded', 'Museum days', 'Matcha mornings', 'Wellness-minded'],
    coffeeMeetupPreferences: {
      meetupStyle: ['Quick coffee (30 min)', 'Walk + coffee'],
      favoriteSpots: ['Sey Coffee', 'Cafe Erzulie'],
    },
    comfortSignals: {
      strollerFriendlyOnly: false,
      playgroundAndCafe: 'Either',
      indoorCafeComfort: 'Yes',
    },
    safety: { phoneVerified: true, referredByMember: false, neighborhoodHost: false },
    socialProof: { mutualConnectionsCount: 2, successfulMeetupsCount: 3 },
  },
  {
    id: 'mom_3',
    name: 'Rachel Kim',
    age: 29,
    neighborhood: 'Park Slope',
    bio: 'First-time mom navigating it all with humor and too much coffee. Looking for mom friends who keep it real.',
    interests: ['Running', 'Podcasts', 'Coffee', 'Dogs', 'Brunch'],
    kids: [{ name: 'Ethan', age: 1, ageLabel: '10 months', gender: 'boy' }],
    avatar: '',
    photos: [],
    verified: true,
    hangNow: true,
    lastActive: '2m ago',
    prompts: [
      { question: 'My ideal coffee catch-up looks like...', answer: 'A stroller walk through the park, then a calm cappuccino and adult conversation.' },
      { question: 'A fun fact about me...', answer: 'I ran a half marathon at 6 months pregnant. My doctor said I was crazy. She was right.' },
      { question: 'On weekends you\'ll find us at...', answer: 'The farmer\'s market or any cafe with a stroller-friendly entrance.' },
    ],
    vibeTags: ['Running stroller', 'Newborn haze', 'Podcast person', 'Cappuccino person', 'Stroller walks'],
    coffeeMeetupPreferences: {
      meetupStyle: ['Walk + coffee', 'Quick coffee (30 min)'],
      favoriteSpots: ['Cafe Regular', 'Hungry Ghost', 'Roots Cafe'],
    },
    comfortSignals: {
      strollerFriendlyOnly: true,
      playgroundAndCafe: 'Playground first',
      indoorCafeComfort: 'Sometimes',
    },
    safety: { phoneVerified: true, referredByMember: true, neighborhoodHost: false },
    socialProof: { mutualConnectionsCount: 4, successfulMeetupsCount: 2, ratingAverage: 5.0 },
  },
  {
    id: 'mom_4',
    name: 'Daniela Ruiz',
    age: 31,
    neighborhood: 'Cobble Hill',
    bio: 'Bilingual mama raising bilingual babies. Love organizing group outings and finding hidden gem restaurants in Brooklyn.',
    interests: ['Languages', 'Travel', 'Cooking', 'Reading', 'Dancing'],
    kids: [
      { name: 'Sofia', age: 3, ageLabel: '3 yrs', gender: 'girl' },
      { name: 'Mateo', age: 5, ageLabel: '5 yrs', gender: 'boy' },
    ],
    avatar: '',
    photos: [],
    verified: true,
    hangNow: false,
    lastActive: '1h ago',
    prompts: [
      { question: 'The way to my heart is...', answer: 'Speaking to my kids in Spanish and suggesting a spontaneous picnic.' },
      { question: 'Currently into...', answer: 'Children\'s books in different languages and finding authentic tacos in Brooklyn.' },
      { question: 'Before kids, I was...', answer: 'A travel writer based in Buenos Aires. Now Brooklyn is my world, and it\'s pretty great.' },
    ],
    vibeTags: ['Language immersion', 'Foodie mom', 'Travel dreams', 'Weekend markets', 'City kid adventures'],
    coffeeMeetupPreferences: {
      meetupStyle: ['Long sit-down chat', 'Walk + coffee', 'Kid-free evening drink'],
      favoriteSpots: ['Brooklyn Roasting Co', 'Cafe Mogador'],
    },
    comfortSignals: {
      strollerFriendlyOnly: false,
      playgroundAndCafe: 'Either',
      indoorCafeComfort: 'Yes',
    },
    safety: { phoneVerified: true, referredByMember: true, neighborhoodHost: true },
    socialProof: { mutualConnectionsCount: 6, successfulMeetupsCount: 12, ratingAverage: 4.9 },
  },
  {
    id: 'mom_5',
    name: 'Priya Sharma',
    age: 33,
    neighborhood: 'Boerum Hill',
    bio: 'Tech product manager by day, toddler wrangler by night. Passionate about creating meaningful connections for our little community.',
    interests: ['Technology', 'Meditation', 'Hiking', 'Board Games', 'Tea'],
    kids: [{ name: 'Arjun', age: 2, ageLabel: '2 yrs', gender: 'boy' }],
    avatar: '',
    photos: [],
    verified: true,
    hangNow: false,
    lastActive: '45m ago',
    prompts: [
      { question: 'My ideal coffee catch-up looks like...', answer: 'A tech-free afternoon at the park with chai lattes and deep conversations.' },
      { question: 'Something I\'m proud of...', answer: 'Building an app while my toddler napped. It took 847 naps.' },
      { question: 'Currently into...', answer: 'Breathwork classes, board game nights, and discovering hidden trails in Prospect Park.' },
    ],
    vibeTags: ['Wellness-minded', 'Deep chats', 'Pilates', 'Work in progress', 'Introvert energy'],
    coffeeMeetupPreferences: {
      meetupStyle: ['Quick coffee (30 min)', 'Long sit-down chat'],
      favoriteSpots: ['Variety Coffee', 'Black Fox Coffee'],
    },
    comfortSignals: {
      strollerFriendlyOnly: false,
      playgroundAndCafe: 'Cafe first',
      indoorCafeComfort: 'Yes',
    },
    safety: { phoneVerified: true, referredByMember: false, neighborhoodHost: false },
    socialProof: { mutualConnectionsCount: 1, successfulMeetupsCount: 4, ratingAverage: 4.7 },
  },
  {
    id: 'mom_6',
    name: 'Emily Watson',
    age: 35,
    neighborhood: 'Windsor Terrace',
    bio: 'Elementary school teacher and mom of twins. I have infinite patience... most of the time. Love nature walks and storytime at the library.',
    interests: ['Reading', 'Nature', 'Crafts', 'Gardening', 'Photography'],
    kids: [
      { name: 'Lily', age: 4, ageLabel: '4 yrs', gender: 'girl' },
      { name: 'Rose', age: 4, ageLabel: '4 yrs', gender: 'girl' },
    ],
    avatar: '',
    photos: [],
    verified: true,
    hangNow: true,
    lastActive: '10m ago',
    prompts: [
      { question: 'My ideal coffee catch-up looks like...', answer: 'A quiet table at a cafe with outdoor seating while the girls draw. Maybe some pastries.' },
      { question: 'A fun fact about me...', answer: 'I can tell my identical twins apart by their laughs. It took me 6 months.' },
      { question: 'On weekends you\'ll find us at...', answer: 'The Brooklyn Botanic Garden or the library for Saturday storytime.' },
    ],
    vibeTags: ['Library storytime', 'Park strolls', 'Gentle parenting', 'Book club vibes', 'Crafts'],
    coffeeMeetupPreferences: {
      meetupStyle: ['Walk + coffee', 'Long sit-down chat'],
      favoriteSpots: ['Cafe Martin', 'Steeplechase Coffee'],
    },
    comfortSignals: {
      strollerFriendlyOnly: false,
      playgroundAndCafe: 'Playground first',
      indoorCafeComfort: 'Prefer outdoors',
    },
    safety: { phoneVerified: true, referredByMember: true, neighborhoodHost: true },
    socialProof: { mutualConnectionsCount: 7, successfulMeetupsCount: 15, ratingAverage: 5.0 },
  },
];

export const allMoms: Mom[] = [currentUser, ...discoveryMoms];

export function getMomById(id: string): Mom | undefined {
  return allMoms.find(m => m.id === id);
}

export const initialMatches: Match[] = [
  {
    id: 'match_1',
    momId: 'mom_1',
    matched: true,
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    lastMessage: 'Would love to meet at that new cafe on Smith St!',
    unread: 1,
  },
  {
    id: 'match_2',
    momId: 'mom_3',
    matched: true,
    timestamp: new Date(Date.now() - 172800000).toISOString(),
    lastMessage: 'See you at the park tomorrow at 10am?',
    unread: 0,
  },
];

export const initialMessages: Message[] = [
  {
    id: 'msg_1',
    matchId: 'match_1',
    senderId: 'mom_1',
    content: 'Hi Sarah! I noticed we\'re both in the neighborhood. My Oliver loves the playground at Carroll Park.',
    timestamp: new Date(Date.now() - 90000000).toISOString(),
    read: true,
  },
  {
    id: 'msg_2',
    matchId: 'match_1',
    senderId: CURRENT_USER_ID,
    content: 'That\'s so close to us! We should definitely meet up there sometime.',
    timestamp: new Date(Date.now() - 89000000).toISOString(),
    read: true,
  },
  {
    id: 'msg_3',
    matchId: 'match_1',
    senderId: 'mom_1',
    content: 'Would love to meet at that new cafe on Smith St!',
    timestamp: new Date(Date.now() - 87000000).toISOString(),
    read: false,
  },
  {
    id: 'msg_4',
    matchId: 'match_2',
    senderId: 'mom_3',
    content: 'Hey! Fellow Park Slope mom here. Love your profile!',
    timestamp: new Date(Date.now() - 200000000).toISOString(),
    read: true,
  },
  {
    id: 'msg_5',
    matchId: 'match_2',
    senderId: CURRENT_USER_ID,
    content: 'Thanks Rachel! We should totally meet up. My kids love the Long Meadow.',
    timestamp: new Date(Date.now() - 190000000).toISOString(),
    read: true,
  },
  {
    id: 'msg_6',
    matchId: 'match_2',
    senderId: 'mom_3',
    content: 'See you at the park tomorrow at 10am?',
    timestamp: new Date(Date.now() - 180000000).toISOString(),
    read: true,
  },
];

export const initialPosts: Post[] = [
  {
    id: 'post_1',
    authorId: 'mom_1',
    content: 'Found the cutest little cafe on Court St with an actual play corner! The barista even made Oliver a "baby-ccino" with steamed milk and cinnamon.',
    locationName: 'Tiny Cup Cafe',
    likes: 12,
    comments: [
      { id: 'c1', authorId: 'mom_3', content: 'Oh I need to check this out!', timestamp: new Date(Date.now() - 3600000).toISOString() },
    ],
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    type: 'checkin',
    liked: false,
  },
  {
    id: 'post_2',
    authorId: 'mom_2',
    content: 'Art afternoon at Brooklyn Museum was a hit! Zara made friends with three other kids in the family workshop. Any moms want to join next Saturday?',
    likes: 8,
    comments: [],
    timestamp: new Date(Date.now() - 14400000).toISOString(),
    type: 'meetup',
    liked: true,
  },
  {
    id: 'post_3',
    authorId: 'mom_6',
    content: 'Prospect Park morning crew! The twins discovered ducks today and now they want to live at the lake. Beautiful day for a walk.',
    locationName: 'Prospect Park',
    likes: 15,
    comments: [
      { id: 'c2', authorId: 'mom_4', content: 'We were there too! Should have said hi!', timestamp: new Date(Date.now() - 10800000).toISOString() },
      { id: 'c3', authorId: 'mom_5', content: 'The ducks are the best part of the park honestly', timestamp: new Date(Date.now() - 9000000).toISOString() },
    ],
    timestamp: new Date(Date.now() - 21600000).toISOString(),
    type: 'checkin',
    liked: false,
  },
  {
    id: 'post_4',
    authorId: 'mom_5',
    content: 'Looking for 2-3 moms who want to start a weekly meditation + playdate group in Boerum Hill. Kids play, we zen out (or try to). Who\'s in?',
    likes: 22,
    comments: [
      { id: 'c4', authorId: 'mom_2', content: 'Count me in!', timestamp: new Date(Date.now() - 28800000).toISOString() },
    ],
    timestamp: new Date(Date.now() - 36000000).toISOString(),
    type: 'meetup',
    liked: true,
  },
];

export const locations: Location[] = [
  {
    id: 'loc_1',
    name: 'Tiny Cup Cafe',
    type: 'cafe',
    address: '234 Court St, Carroll Gardens',
    latitude: 40.6862,
    longitude: -73.9936,
    rating: 4.8,
    checkins: 47,
    kidFriendly: true,
    amenities: ['Play Corner', 'High Chairs', 'Changing Table', 'Stroller Parking'],
  },
  {
    id: 'loc_2',
    name: 'Prospect Park Playground',
    type: 'playground',
    address: 'Prospect Park, Park Slope',
    latitude: 40.6602,
    longitude: -73.9690,
    rating: 4.9,
    checkins: 156,
    kidFriendly: true,
    amenities: ['Swings', 'Sandbox', 'Water Feature', 'Shaded Areas'],
  },
  {
    id: 'loc_3',
    name: 'Brooklyn Roasting Co',
    type: 'cafe',
    address: '200 Flushing Ave, Navy Yard',
    latitude: 40.6975,
    longitude: -73.9765,
    rating: 4.6,
    checkins: 34,
    kidFriendly: true,
    amenities: ['Spacious', 'Stroller Friendly', 'Outdoor Seating'],
  },
  {
    id: 'loc_4',
    name: 'Carroll Park',
    type: 'park',
    address: 'Carroll St & Smith St, Carroll Gardens',
    latitude: 40.6808,
    longitude: -73.9934,
    rating: 4.7,
    checkins: 89,
    kidFriendly: true,
    amenities: ['Playground', 'Sprinklers', 'Basketball Court', 'Dog Area'],
  },
  {
    id: 'loc_5',
    name: 'BookCourt Kids',
    type: 'library',
    address: '163 Court St, Cobble Hill',
    latitude: 40.6880,
    longitude: -73.9935,
    rating: 4.5,
    checkins: 28,
    kidFriendly: true,
    amenities: ['Story Time', 'Kids Section', 'Reading Nook'],
  },
  {
    id: 'loc_6',
    name: 'Ample Hills Creamery',
    type: 'restaurant',
    address: '623 Vanderbilt Ave, Prospect Heights',
    latitude: 40.6780,
    longitude: -73.9685,
    rating: 4.8,
    checkins: 63,
    kidFriendly: true,
    amenities: ['Kid Sizes', 'Allergy Friendly', 'Indoor Seating'],
  },
];

export const wriggleClasses: Location[] = [
  {
    id: 'class_1',
    name: 'Music for Aardvarks',
    type: 'class',
    address: '472 Bergen St, Park Slope',
    latitude: 40.6810,
    longitude: -73.9760,
    rating: 4.9,
    checkins: 34,
    kidFriendly: true,
    amenities: ['Music', 'Interactive', '0-4 yrs'],
    classInfo: {
      provider: 'Audra Rox',
      venue: 'The Canopy',
      category: 'music',
      ageRange: 'Birth to 4 years',
      ageMinMonths: 0,
      ageMaxMonths: 48,
      daysOfWeek: ['Thu', 'Fri', 'Mon'],
      description: 'A joyful, interactive music class where families sing, move and play.',
      sourceUrl: 'https://www.thewriggle.com/babies',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_2',
    name: 'Songs for Seeds',
    type: 'class',
    address: '321 Court St, Carroll Gardens',
    latitude: 40.6830,
    longitude: -73.9940,
    rating: 4.8,
    checkins: 28,
    kidFriendly: true,
    amenities: ['Music', 'Sing-along', '0-4 yrs'],
    classInfo: {
      provider: 'Songs for Seeds',
      venue: 'Grind House',
      category: 'music',
      ageRange: 'Birth to 4 years',
      ageMinMonths: 0,
      ageMaxMonths: 48,
      daysOfWeek: ['Tue', 'Wed', 'Thu'],
      description: 'Sing, dance and play along to original tunes and pop/rock songs.',
      sourceUrl: 'https://www.thewriggle.com/babies',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_3',
    name: 'Baby and Me Yoga',
    type: 'class',
    address: '260 Court St, Cobble Hill',
    latitude: 40.6836,
    longitude: -73.9915,
    rating: 4.7,
    checkins: 19,
    kidFriendly: true,
    amenities: ['Yoga', 'Postnatal', '0-12 mo'],
    classInfo: {
      provider: 'Sparsa',
      venue: 'Sparsa',
      category: 'yoga',
      ageRange: '0 to 12 months',
      ageMinMonths: 0,
      ageMaxMonths: 12,
      daysOfWeek: ['Tue', 'Thu'],
      description: 'Bring your baby yoga class centered around postpartum needs.',
      sourceUrl: 'https://www.thewriggle.com/babies',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_4',
    name: 'Puppetsburg',
    type: 'class',
    address: '361 7th Ave, Park Slope',
    latitude: 40.6721,
    longitude: -73.9795,
    rating: 4.9,
    checkins: 41,
    kidFriendly: true,
    amenities: ['Puppets', 'Interactive', '4mo-4yrs'],
    classInfo: {
      provider: 'Puppetsburg',
      venue: 'The Wild',
      category: 'puppetry',
      ageRange: '4 months to 4 years',
      ageMinMonths: 4,
      ageMaxMonths: 48,
      daysOfWeek: ['Tue', 'Wed', 'Thu'],
      description: 'Culturally relevant puppet shows for children 4 months to 4 years.',
      sourceUrl: 'https://www.thewriggle.com/babies',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_5',
    name: 'Open Play',
    type: 'class',
    address: '297 5th Ave, Park Slope',
    latitude: 40.6769,
    longitude: -73.9787,
    rating: 4.6,
    checkins: 67,
    kidFriendly: true,
    amenities: ['Free Play', 'Indoor', 'Daily'],
    classInfo: {
      provider: 'The Play Lab',
      venue: 'The Play Lab',
      category: 'open-play',
      ageRange: '0 to 4 years',
      ageMinMonths: 0,
      ageMaxMonths: 48,
      daysOfWeek: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
      description: 'You and your child can enjoy our playspace every day.',
      sourceUrl: 'https://www.thewriggle.com/babies',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_6',
    name: 'Baby Fingers',
    type: 'class',
    address: '361 7th Ave, Park Slope',
    latitude: 40.6723,
    longitude: -73.9793,
    rating: 4.8,
    checkins: 22,
    kidFriendly: true,
    amenities: ['Sign Language', 'Music', '0-12 mo'],
    classInfo: {
      provider: 'The Wild',
      venue: 'The Wild',
      category: 'language',
      ageRange: '0 to 12 months',
      ageMinMonths: 0,
      ageMaxMonths: 12,
      daysOfWeek: ['Mon'],
      description: 'Sing, sign, and bond with your baby supporting early language.',
      sourceUrl: 'https://www.thewriggle.com/babies',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_7',
    name: 'Messy Sensory Play',
    type: 'class',
    address: '190 Flatbush Ave, Prospect Heights',
    latitude: 40.6862,
    longitude: -73.9754,
    rating: 4.7,
    checkins: 31,
    kidFriendly: true,
    amenities: ['Sensory', 'Art', '1-3 yrs'],
    classInfo: {
      provider: 'A Rosie Day',
      venue: 'A Rosie Day',
      category: 'sensory',
      ageRange: '1 to 3 years',
      ageMinMonths: 12,
      ageMaxMonths: 36,
      daysOfWeek: ['Wed', 'Sat'],
      description: 'Encourages sensory exploration, creativity, and social interaction in a safe environment.',
      sourceUrl: 'https://www.thewriggle.com/toddlers',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_8',
    name: 'Infant Developmental Movement',
    type: 'class',
    address: '361 7th Ave, Park Slope',
    latitude: 40.6725,
    longitude: -73.9791,
    rating: 4.8,
    checkins: 15,
    kidFriendly: true,
    amenities: ['Movement', 'Development', '0-12 mo'],
    classInfo: {
      provider: 'Embodied Mother',
      venue: 'The Wild',
      category: 'movement',
      ageRange: '0 to 12 months',
      ageMinMonths: 0,
      ageMaxMonths: 12,
      daysOfWeek: ['Sat', 'Tue'],
      description: 'Nurture baby\'s learning through gentle handling and play.',
      sourceUrl: 'https://www.thewriggle.com/babies',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_9',
    name: 'Little Gym',
    type: 'class',
    address: '635 Vanderbilt Ave, Prospect Heights',
    latitude: 40.6890,
    longitude: -73.9680,
    rating: 4.6,
    checkins: 25,
    kidFriendly: true,
    amenities: ['Gymnastics', 'Movement', '1-3 yrs'],
    classInfo: {
      provider: 'Little Gym',
      venue: 'Artudio',
      category: 'movement',
      ageRange: '1 to 3 years',
      ageMinMonths: 12,
      ageMaxMonths: 36,
      daysOfWeek: ['Mon', 'Wed', 'Fri'],
      description: 'Introduce little ones to fitness with gymnastics, yoga, and creative movement.',
      sourceUrl: 'https://www.thewriggle.com/toddlers',
      lastSyncedAt: new Date().toISOString(),
    },
  },
  {
    id: 'class_10',
    name: 'Lactation Support Group',
    type: 'class',
    address: '361 7th Ave, Park Slope',
    latitude: 40.6719,
    longitude: -73.9797,
    rating: 4.9,
    checkins: 18,
    kidFriendly: true,
    amenities: ['Support', 'Lactation', 'Newborn'],
    classInfo: {
      provider: 'The Wild',
      venue: 'The Wild',
      category: 'wellness',
      ageRange: '0 to 6 months',
      ageMinMonths: 0,
      ageMaxMonths: 6,
      daysOfWeek: ['Fri'],
      description: 'Help with latch, supply, pumping with baby weigh-ins.',
      sourceUrl: 'https://www.thewriggle.com/babies',
      lastSyncedAt: new Date().toISOString(),
    },
  },
];

// Combine locations and classes for unified access
locations.push(...wriggleClasses);

export const badges: Badge[] = [
  { id: 'badge_1', name: 'First Steps', icon: 'footprints', description: 'Made your first connection', earned: true, earnedDate: '2025-01-15' },
  { id: 'badge_2', name: 'Cafe Explorer', icon: 'cafe', description: 'Checked in at 3 different cafes', earned: true, earnedDate: '2025-02-01' },
  { id: 'badge_3', name: 'Park Regular', icon: 'leaf', description: 'Visited a park 5 times', earned: false },
  { id: 'badge_4', name: 'Social Butterfly', icon: 'chatbubbles', description: 'Started 10 conversations', earned: false },
  { id: 'badge_5', name: 'Neighborhood Star', icon: 'star', description: 'Got 5 likes on a post', earned: true, earnedDate: '2025-02-10' },
];
